package openai

// These trusted names are the only variable instruction content. Unsupported
// regions/scripts are never inferred or copied from caller-supplied strings.
var languageDisplayNames = map[string]string{
	"ar":    "Arabic",
	"bg":    "Bulgarian",
	"cs":    "Czech",
	"da":    "Danish",
	"de":    "German",
	"el":    "Greek",
	"en":    "English",
	"es":    "Spanish",
	"et":    "Estonian",
	"fi":    "Finnish",
	"fr":    "French",
	"he":    "Hebrew",
	"hi":    "Hindi",
	"hu":    "Hungarian",
	"id":    "Indonesian",
	"it":    "Italian",
	"ja":    "Japanese",
	"ko":    "Korean",
	"lt":    "Lithuanian",
	"lv":    "Latvian",
	"nb":    "Norwegian Bokmål",
	"nl":    "Dutch",
	"pl":    "Polish",
	"pt":    "Portuguese",
	"pt-BR": "Brazilian Portuguese",
	"ro":    "Romanian",
	"ru":    "Russian",
	"sk":    "Slovak",
	"sl":    "Slovenian",
	"sv":    "Swedish",
	"th":    "Thai",
	"tr":    "Turkish",
	"uk":    "Ukrainian",
	"vi":    "Vietnamese",
	"zh-CN": "Simplified Chinese",
	"zh-TW": "Traditional Chinese",
}
