package deepl

// canonicalToDeepLSource is deliberately separate from the target map.
// DeepL accepts generic source identifiers for Chinese and Portuguese even
// when the canonical request identifies a particular variant.
var canonicalToDeepLSource = map[string]string{
	"ar":    "AR",
	"bg":    "BG",
	"cs":    "CS",
	"da":    "DA",
	"de":    "DE",
	"el":    "EL",
	"en":    "EN",
	"es":    "ES",
	"et":    "ET",
	"fi":    "FI",
	"fr":    "FR",
	"he":    "HE",
	"hi":    "HI",
	"hu":    "HU",
	"id":    "ID",
	"it":    "IT",
	"ja":    "JA",
	"ko":    "KO",
	"lt":    "LT",
	"lv":    "LV",
	"nb":    "NB",
	"nl":    "NL",
	"pl":    "PL",
	"pt":    "PT",
	"pt-BR": "PT",
	"ro":    "RO",
	"ru":    "RU",
	"sk":    "SK",
	"sl":    "SL",
	"sv":    "SV",
	"th":    "TH",
	"tr":    "TR",
	"uk":    "UK",
	"vi":    "VI",
	"zh-CN": "ZH",
	"zh-TW": "ZH",
}

// canonicalToDeepLTarget preserves target variants that DeepL distinguishes.
// Every accepted canonical tag is listed explicitly; regions are never
// stripped or inferred.
var canonicalToDeepLTarget = map[string]string{
	"ar":    "AR",
	"bg":    "BG",
	"cs":    "CS",
	"da":    "DA",
	"de":    "DE",
	"el":    "EL",
	"en":    "EN",
	"es":    "ES",
	"et":    "ET",
	"fi":    "FI",
	"fr":    "FR",
	"he":    "HE",
	"hi":    "HI",
	"hu":    "HU",
	"id":    "ID",
	"it":    "IT",
	"ja":    "JA",
	"ko":    "KO",
	"lt":    "LT",
	"lv":    "LV",
	"nb":    "NB",
	"nl":    "NL",
	"pl":    "PL",
	"pt":    "PT",
	"pt-BR": "PT-BR",
	"ro":    "RO",
	"ru":    "RU",
	"sk":    "SK",
	"sl":    "SL",
	"sv":    "SV",
	"th":    "TH",
	"tr":    "TR",
	"uk":    "UK",
	"vi":    "VI",
	"zh-CN": "ZH-HANS",
	"zh-TW": "ZH-HANT",
}

var deepLToCanonical = map[string]string{
	"AR": "ar",
	"BG": "bg",
	"CS": "cs",
	"DA": "da",
	"DE": "de",
	"EL": "el",
	"EN": "en",
	"ES": "es",
	"ET": "et",
	"FI": "fi",
	"FR": "fr",
	"HE": "he",
	"HI": "hi",
	"HU": "hu",
	"ID": "id",
	"IT": "it",
	"JA": "ja",
	"KO": "ko",
	"LT": "lt",
	"LV": "lv",
	"NB": "nb",
	"NL": "nl",
	"PL": "pl",
	"PT": "pt",
	"RO": "ro",
	"RU": "ru",
	"SK": "sk",
	"SL": "sl",
	"SV": "sv",
	"TH": "th",
	"TR": "tr",
	"UK": "uk",
	"VI": "vi",
	"ZH": "zh-CN",
}
